name: Deploy index.html to Azure Web App - npi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_79781D6E340E40B7895D2150E128BA4A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F9CBB90BDAC14AFC964FFDC5EF1E9D98 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4E411292529C4EB1BFE9947011E41B41 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: npi
          slot-name: Production
          package: .
